### ISSUE TITLE
Person entities do not show photo

### ISSUE THREAD

**Issue by tobycth3** [nathan-gs/ha-map-card#1]
When using person.NAME as entity, the photo for the tracker does not now, instead just the first letter is displayed

entities:
  - person.NAME

**Comment by nathan-gs** [comment]
@tobycth3 in v0.3.0 I added support for pictures!

**Comment by Elu43** [comment]
@nathan-gs Hello, thank you so much for this card, I've been waiting for years to be able to change this map.


I cannot display entity's picture as well. With "icon" option I have the first letter, but with "marker" I have nothing.
I'm using v0.4.0. Is it still working on your side ?

Best regards

**Comment by nathan-gs** [comment]
@Elu43 are you sure the entity has a picture (what do you see if you click on the marker)?

Here it still works.

**Comment by Elu43** [comment]
@nathan-gs Yes, my entity have a picture, I can see it on the "classic" HA map.

But here nothing appears, no circle, no pic, blank like it doesn't exist. But the view is centered correctly on my location, and when I run my cursor over the supposed location, the cursor changes into a pointing finger and a tooltip with my entity's name appears :

![image](https://github.com/nathan-gs/ha-map-card/assets/45129108/bd6c251d-9c94-40c3-8a34-621115fadf8d)

Actually it worked once without any config change, but when I refreshed the page it was not working anymore, I have no idea why.

The problem is the same on PC and Android companion app. I'm using Docker.

I don't know if it's related but when I open the page with the map, the map tiles are very laggy to appear during the first 10 seconds, but then there is no loading problem everywhere on the map.

I have no idea where to look to troubleshoot this. Is there specifications for the pictire ? (size, format). Or maybe permission problem to load these pictures ?

My config :

```
type: custom:map-card
card_size: 15
tile_layer_url: https://a.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png
entities:
  - entity: person.xxxx
    display: marker
```

Best regards

**Comment by ildar170975** [comment]
@nathan-gs 
Hi! Thanks a lot for the card!

I do not see entity_picture as well:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/45907a8b-219d-48f7-bbc9-c10ee602e605)
```
type: custom:map-card
entities:
  - entity: person.ildar
    display: marker
```
```
type: custom:map-card
entities:
  - entity: person.ildar
    display: icon
```
 And same "cure": add a stock map card - then the picture is shown:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/e4e36563-08a9-460e-becc-6471a5e4070e)

Remove the map card -> refresh the page (F5) -> again no picture displayed.
