### ISSUE TITLE
[FR] Colorize an icon independently

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#107]
(moved from https://github.com/nathan-gs/ha-map-card/issues/74#issuecomment-2327539157)

In https://github.com/nathan-gs/ha-map-card/issues/74 it was suggested to colorize an icon.
Unfortunately, in some cases it could be undesirable.
Consider the code:
```
  - type: custom:map-card
    entities:
      - entity: device_tracker.iphone_5s_traccar
        color: red
        <<: &ref_settings
          display: icon
          history_start: 12 hours ago
          history_end: now
      - entity: device_tracker.iphone_5s_32_traccar
        <<: *ref_settings
        color: green
    tile_layer_url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    card_size: 10
```
Here we can see:
-- tracks of different colors;
-- circles of same colors as tracks;
-- icons of same colors as tracks.
![image](https://github.com/user-attachments/assets/92a0c5a4-5b6d-4b43-b191-9741ec18ad66)

A stock Map card will show:
-- tracks of different colors;
-- circles of same colors as tracks;
-- icons of SAME DEFAULT color.
Example with a stock Map is below (the map itself is hidden):
![image](https://github.com/user-attachments/assets/4d3a9214-22fb-4669-82a3-25238417e2df)

So, in some cases colors of tracks should be different, not colors of icons - circles of different colors could be rather enough.

It could be even this with some default colors (if color options are not set):
![364162279-6a350811-e6d5-4fc7-9ed4-69fb4fd020a8](https://github.com/user-attachments/assets/501de9e7-583c-42a2-bd9a-cf520e2cfd3b)
where you cannot see an icon at all.

**Proposal**:
Add a new option like `set_icon_color` (true/false), default is `true` (to not break the current behaviour).
If `true` - then the color is used for an icon too.
if `false` - then use `var(--primary-text-color)` (like in a stock Map card).
