### ISSUE TITLE
Display Polygon Layers from External source

### ISSUE THREAD

**Issue by nathan-gs** [nathan-gs/ha-map-card#117]
>
> Leaflet supports path, polyline, and polygon layers, in addition to wms. Is it possible for this card to plot polygons?
> 
> This is the data I’m looking to integrate:
> https://data-nifc.opendata.arcgis.com/datasets/nifc::wfigs-2025-interagency-fire-perimeters-to-date/about

By **[tailormade](https://community.home-assistant.io/u/taylormade)** in https://community.home-assistant.io/t/map-card-a-slightly-improved-map-card/693088/57

**Comment by nathan-gs** [comment]
Could be linked to #108

**Comment by nathan-gs** [comment]
https://leafletjs.com/examples/geojson/

**Comment by holdestmade** [comment]
If you still need this, this is a plugin to do it. You need to put a geojson file ( I used https://geojson.io to generate the polygon file) in `www `and point to it. Don't forget to add a resource as well


```
type: custom:map-card
zoom: 17
x: xxxxxxx
y: xxxxxxx
plugins:
  - name: geojson-polygon-plugin
    url: /local/ha-map-card-geojson-polygon-plugin.js
    options:
      geojsonUrl: /local/home_poly_zone.json

```
```
export default function(L, pluginBase, Logger) {
  return class GeoJsonPolygonPlugin extends pluginBase {
    constructor(map, name, options = {}) {
      super(map, name, options);

      const { geojsonUrl, style, ...otherOptions } = options;

      if (!geojsonUrl) {
        Logger.error(`[${this.name}] 'geojsonUrl' is missing from plugin options. Please provide a URL to your GeoJSON file.`);
      }

      this.geojsonUrl = geojsonUrl;
      this.style = style;
      this.otherOptions = otherOptions;
      this.geoJsonLayer = null;
      this.geojson = null;

      Logger.debug(`[${this.name}] Successfully invoked constructor with options:`, this.options);
    }

    async init() {
      Logger.debug(`[${this.name}] Called init(). Fetching GeoJSON from: ${this.geojsonUrl}`);

      if (!this.geojsonUrl) {
        Logger.warn(`[${this.name}] No geojsonUrl provided. Cannot fetch data.`);
        return;
      }

      try {
        const response = await fetch(this.geojsonUrl);
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status} for URL: ${this.geojsonUrl}`);
        }
        this.geojson = await response.json();
        Logger.debug(`[${this.name}] Successfully fetched GeoJSON data:`, this.geojson);
      } catch (error) {
        Logger.error(`[${this.name}] Error fetching GeoJSON from ${this.geojsonUrl}:`, error);
        this.geojson = null;
      }
    }

    async renderMap() {
      Logger.debug(`[${this.name}] Called renderMap()`);

      if (!this.geojson) {
        Logger.warn(`[${this.name}] No GeoJSON data available to render. Ensure 'geojsonUrl' is correct and data is fetched.`);
        return;
      }

      if (this.geoJsonLayer) {
        this.geoJsonLayer.remove();
        this.geoJsonLayer = null;
      }

      try {
        this.geoJsonLayer = L.geoJSON(this.geojson, {
          style: (feature) => {
            return this.style || {
              color: '#ff7800',
              weight: 5,
              opacity: 0.65,
              fillColor: '#ff7800',
              fillOpacity: 0.2
            };
          },
          onEachFeature: (feature, layer) => {
            if (feature.properties && feature.properties.name) {
              layer.bindPopup(feature.properties.name);
            }
          }
        }).addTo(this.map);

        Logger.info(`[${this.name}] GeoJSON layer added to map. Number of features: ${this.geojson.features ? this.geojson.features.length : 'N/A'}`);

      } catch (error) {
        Logger.error(`[${this.name}] Error rendering GeoJSON:`, error);
      }
    }

    async update() {
      Logger.debug(`[${this.name}] Called update()`);
    }

    destroy() {
      Logger.debug(`[${this.name}] Called destroy()`);
      if (this.geoJsonLayer) {
        this.geoJsonLayer.remove();
        this.geoJsonLayer = null;
      }
      this.geojson = null;
    }
  };
}

```

**Comment by nathan-gs** [comment]
@holdestmade very cool! Could you create a repo with this and add a PR to the readme listing it? Thanks!!!

**Comment by nathan-gs** [comment]
Follow-up from #177 (closed as superseded — the work landed via #192).

Polygons, LineStrings, and FeatureCollections from a Home Assistant entity are now first-class. Two ways:

**On an entity** (draws the shape next to / instead of the marker):

```yaml
type: custom:map-card
entities:
  - entity: sensor.fire_perimeters
    geojson:
      attribute: geometry
      color: '#ff7800'
      fill_opacity: 0.25
      hide_marker: true
```

**As a card-level layer** (no marker; nested attribute paths work):

```yaml
type: custom:map-card
x: -122.4
y: 37.8
zoom: 6
geojson:
  - entity: sensor.nifc_perimeters
    attribute: features
    color: '#ff7800'
    fill_color: '#ff7800'
    fill_opacity: 0.2
```

Supported types: Point, LineString, Polygon, Multi*, GeometryCollection, Feature, FeatureCollection. Features are clickable (`tap_action` / more-info) and show Feature `properties` on hover.

What is still plugin-only: loading a **static file** (`/local/home_poly_zone.json`) or an arbitrary HTTP GeoJSON URL. @holdestmade's plugin in this thread is still the right approach for that. If the source is already an HA entity (NWS alerts, polygonal-zones addon, a REST sensor), use the native `geojson:` key instead.

Leaving this open for the external-URL case.
