### ISSUE TITLE
2 Lines when history_start is an entity

### ISSUE THREAD

**Issue by H4X0-R** [nathan-gs/ha-map-card#128]
Since the update from mapcard 1.11 to 1.12 there are 2 lines when the history_start is set to an entity. If i manually set history_start the to state of my variable, it only shows 1 line as its supposed
Installing an old version (1.11) works with the same yaml and there are only 1 line again. Updating to the newest version brings back the second line.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

type: custom:map-card
entities:
  - entity: person.xxx
    use_base_entity_only: true
    history_start: sensor.date

# End of code
```

State of "sensor.date" is "2025-01-27"
