### ISSUE TITLE
Follow_focus/Autofit zoom only

### ISSUE THREAD

**Issue by digifiel** [nathan-gs/ha-map-card#140]
Feature request:

Keep the map centered on the coördinates or focus_entity and only use zoom to fit entities.

Extra nice would be if you could set a radius beyond which a enity will be ignored.

**Comment by caitotheonlypotato** [comment]
Not sure if my issue is similar, If I use in conjunction with custom:auto-entities as an example to display zones in addition to the device tracker entity, the card seems to be force zoomed out to the boundary that contains all zones, whereas I'd rather be able to set the zoom boundary and focus only on the device tracker entity, so that the device tracker is centered on the map and zones appear on the map as the device tracker passes them.

![Image](https://github.com/user-attachments/assets/3e6195c0-6f73-4513-9b56-ed6783632f24)

**Comment by MasterCATZ** [comment]
<img width="526" height="698" alt="Image" src="https://github.com/user-attachments/assets/6e3b796c-d27e-49b6-9603-4cfc2e65dc87" />

how to get a closer zoom ? 20 seems as far as it will go ~ 700m above ground ? 

```
type: custom:map-card
zoom: 20
maxZoom: 100
focus_entity: device_tracker.lymow_working_mower_position
follow_focus: refocus
entities:
  - entity: device_tracker.lymow_working_mower_position
    display: icon
    size: 20
    color: blue
  - entity: sensor.lymow_working_map_geojson
    geojson:
      attribute: geojson
      filter:
        property: type
        value: zone
      color: "#00c853"
      weight: 2
      opacity: 1
      fill_opacity: 0.25
      hide_marker: true
  - entity: sensor.lymow_working_map_geojson
    geojson:
      attribute: geojson
      filter:
        property: type
        value: mow_path
      color: "#ff6f00"
      weight: 3
      opacity: 0.85
      fill_opacity: 0
      hide_marker: true
  - entity: device_tracker.lymow_working_rtk_base
    geojson:
      attribute: geojson
      filter:
        property: type
        value: dock
      color: "#ffd600"
      hide_marker: false`

```

```
type: custom:map-card
zoom: 20
maxZoom: 22
focus_entity: device_tracker.lymow_working_mower_position
follow_focus: refocus
entities:
  - zone.home
  - person.goldtownaquaponicallygrownfood
  - device_tracker.sm_n920i
  - device_tracker.pixel_6_pro
  - device_tracker.lymow_ef8307_working
  - device_tracker.lymow_ef8307_working_2
  - device_tracker.lymow_two_rtk_base
  - device_tracker.lymow_two_mower_position
  - entity: device_tracker.lymow_working_rtk_base
    display: icon
    size: 20
    color: black
  - entity: device_tracker.lymow_working_mower_position
    display: icon
    size: 20
    color: blue
  - entity: sensor.lymow_xxx_map_geojson
    geojson:
      attribute: geojson_zones
      color: "#00c853"
      weight: 1
      opacity: 1
      fill_opacity: 0.22
      hide_marker: true
  - entity: sensor.lymow_working_map_geojson
    geojson:
      attribute: geojson_nogo_zones
      color: "#ff6f00"
      weight: 2
      opacity: 1
      fill_opacity: 1
      hide_marker: true
  - entity: sensor.lymow_working_map_geojson
    geojson:
      attribute: geojson_mowed_area
      color: "#2196f3"
      weight: 2
      opacity: 0.95
      fill_opacity: 0.35
      hide_marker: true
  - entity: sensor.lymow_working_map_geojson
    geojson:
      attribute: geojson_dock
      color: "#ffd600"
      weight: 3
      opacity: 1
      fill_opacity: 0.6
      hide_marker: true
```
