### ISSUE TITLE
Local Stored Custom Map overlay

### ISSUE THREAD

**Issue by JoshFDXGUS** [nathan-gs/ha-map-card#144]
I am using this for my Mammotion robot mower.  I would like to take a screenshot of my map from the Mammotion app and use it as an overlay for the map.  Is this possible and how would one go about doing such?  

Thanks in advance.

**Comment by JoshuaLampert** [comment]
I came across the same issue. I would like to use a [Non-geographic map](https://leafletjs.com/examples/crs-simple/crs-simple.html). I managed to write a simple plugin, which uses `L.imageOverlay` to display the image. This already shows the image, but I would also need to change the `crs` to `L.CRS.Simple` as explained in [this Leaflet.js example](https://leafletjs.com/examples/crs-simple/crs-simple.html). Ideally, the `crs` could be passed to the `map_options` argument, but since we would need to pass javascript code (`L.CRS.Simple`) my attempts to try that failed. Is there any way to change the `crs` of the map? I'm also happy to share my plugin if someone is interested.

**Comment by nathan-gs** [comment]
@JoshuaLampert would certainly be an interesting plug-in!

**Comment by JoshuaLampert** [comment]
I created the PR #207, which adds the option to create a map with `L.CRS.Simple`. Together with the ImageOverlayPlugin from above, this makes local stored custom map overlays work.

**Comment by nathan-gs** [comment]
Update: the missing piece from this thread is now on `main`.

#207 merged `map_options.crs: simple` (maps the YAML string to Leaflet's `L.CRS.Simple`) and allows `tile_layer_url: \"\"` so the OSM tiles can be turned off. That is exactly the hook @JoshuaLampert needed so an `L.imageOverlay` plugin can use image coordinates instead of lat/lng.

Example:

```yaml
type: custom:map-card
x: 0
y: 0
zoom: 0
map_options:
  crs: simple
  minZoom: -5
tile_layer_url: ""
plugins:
  - name: ImageOverlayPlugin
    url: /local/image-overlay-plugin.js
    options:
      image_path: /local/mower-map.png
entities:
  - entity: vacuum.mower
    fixed_x: 320
    fixed_y: 180
```

The image overlay itself stays a plugin (the snippet earlier in this thread). I'll keep it out of this repo — a small `ha-map-card-plugin` repo is the right place. This issue was already closed; leaving it closed now that the card-side support has actually landed.
