### ISSUE TITLE
Custom element doesn't exist: map-card.

### ISSUE THREAD

**Issue by hensjl** [nathan-gs/ha-map-card#2]
A very good idea, Nathan, but for now, I can't get the map.

Pi4
Core 2024.2.3
Supervisor 2024.02.0
Operating System 11.5
Frontend 20240207.1

Does not exist in HACS

Downloaded button-card.js in www folder

In my lovelace:
```
resources:
  - url: /local/community/button-card/button-card.js
    type: module
  - url: /local/community/lovelace-mushroom/mushroom.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /local/map-card.js
    type: module

```
```
type: custom:map-card
zoom: 8
card_size: 6
wms:
...

```
Custom element doesn't exist: map-card.
