### ISSUE TITLE
[FR] Advanced formatting for a marker

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#40]
Here is a default look for a `person` entity:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/fe8bb3bd-d892-4377-b917-52478cc9f4f7)

Note that a marker has a circle shape (caused by `box-radius: 50%`).
But what if I need to show a phone?
Does not look nice:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/3c33cb01-19b7-45e3-bf8b-58dc534147df)

So, 1st idea - allow to customize `box-radius`.
Assume we got rid of that circle shape by CSS:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/1a9053d2-86d4-4fc2-9fc7-abcdaae299c4)

And now we do not like a background of the marker - so we are using a PNG image with a transparent background.
But it anyway does not look cool - because of an own marker's background.
This can be fixed by CSS as well:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/74439870-1c5f-433c-ba19-f4b2da136971)

Finally, we can remove a border:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/b44601bf-2e62-4187-89a3-421c3191b582)

Suggestion:
Add a NEW option - `style_marker`.
This option can be defined as a dictionary:
```
style_marker:
  xxx: xxx
  xxx: xxx
  xxx: xxx
```
where "xxx: xxx" - CSS styles which should be set directly to a marker.
Imho we should allow a user to define ANY set of styles here - they are just passed to a marker "as is".

By default this option `style_marker` is optional.
It should be defined both per-card & per-entity:
```
type: custom:map-card
entities:
  - entity: ...
    style_marker:
      ...
  - entity: ...
  - entity: ...
    style_marker:
      ...
style_marker:
  ...
```
If defined per-card - then the `style_marker` option is for all markers, unless it is overridden by a `style_marker` option for a particular marker.
