### ISSUE TITLE
FR: Set tile_layers options with template or from entity state

### ISSUE THREAD

**Issue by bezmi** [nathan-gs/ha-map-card#48]
I am trying to use the Rain viewer API to render a rain radar overlay. The URL has a `{time}` field. Would it be possible to get the value for an option from a template or an entity (eg, input_number) and re-render the map smoothly when the value changes (eg, cycling over the last 5 snapshots)?

Currently testing this sort of thing with a `custom:button-card` to add the templating ability. It works, but the map is re-drawn every time the value changes, causing my location markers to pop out and then in as well.

**Comment by nathan-gs** [comment]
@bezmi take a look at [v1.2.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.2.0), in #56 an alternative to this was implemented. Let us know if it does or doesn't fit your use case.

**Comment by bezmi** [comment]
The Rain viewer API expects the `{time}` field to be a plain unix timestamp (seconds since epoch). I believe the current implementation in #56 can only return a timestamp string as it uses `HaMapUtilities.getEntityHistoryDate()`.

When querying the rainviewer API at https://api.rainviewer.com/public/weather-maps.json, the `radar.past` array contains the information to access the last 13 sets of tiles they've generated. I have restful sensor, `sensor.rainviewer_tile_time`, which uses the value of an `input_select` to get  the timestamp of the N-th tileset from the api link above: `radar.past.{input_select number}.time`. Perhaps adding a `convert` boolean to `history` which enables/disables the timestamp conversion would be the easiest way to implement this?

```yaml
type: custom:map-card
x: -27
'y': 152
zoom: 5
tile_layers:
  - url: https://tilecache.rainviewer.com/v2/radar/{time}/256/{z}/{x}/{y}/8/1_0.png
    history:
      property: time
      source: sensor.rainviewer_tile_time # unix timestamp
      convert: false # don't try to convert the value of `source` into a timestamp
```

**Comment by bezmi** [comment]
Yes, I think so. That is what I did before posting this issue, using the templating ability of `button-card`.

**Comment by ildar170975** [comment]
> How about support for arbitrary sensors which you could add to the url?

Imho this is optimal.
Suggest to allow either to use a static `url` option:
```
tile_layers:
  - url: https://...
```
or a corr. entity:
```
Suggest to allow either to use a static `url` option:
```
tile_layers:
  - url_source: sensor.xxx
```

**Comment by nathan-gs** [comment]
Quoting @hyungyunlim in #94: 
> Hello,
> 
> First of all, thank you for your excellent work on the custom map card!
> 
> I'm using the custom map card in Home Assistant to display maps from Naver Maps, a Korean map service provider. Naver Maps requires a version code in the tile_layer_url that changes periodically. To keep the map tiles up to date without manually updating the version code, I attempted to use a sensor in Home Assistant that fetches the latest version code and inserts it into the tile_layer_url dynamically.
> 
> However, it seems that the custom map card does not support templating or placeholders in the tile_layer_url field. When I use a template or a placeholder for the version code, the map does not display—only the device icons appear on a blank background.
> 
> This is how I did.
> 
> **1. Create a Sensor for the Version Code:**
> 
> ```
> sensor:
>   - platform: command_line
>     name: Naver Map Version
>     command: >
>       curl -s 'https://map.pstatic.net/nrb/styles/basic.json?fmt=jpg&mt=bg.ol.ts.ar.lko' |
>       grep -o '"version":"[^"]*"' |
>       head -1 |
>       cut -d '"' -f4
>     scan_interval: 3600  # Update every hour
> ```
> 
> **2. Create a Template Sensor for the Tile URL:**
> 
> ```
> template:
>   - sensor:
>       - name: "Naver Map URL"
>         state: >-
>           https://map.pstatic.net/nrb/styles/basic/{{ states('sensor.naver_map_version') }}/{z}/{x}/{y}@2x.png?mt=bg.ol.ts.ar.lko
> ```
> 
> **3. Configure the Custom Map Card Using the Sensor:**
> 
> ```
> type: custom:map-card
> history_start: 16 hours ago
> auto_fit: true
> tile_layer_url: "{{ states('sensor.naver_map_url') }}"
> tile_layer_attribution: naver.com
> entities:
>   - entity: device_tracker....
>     gradual_opacity: 0.5
>   - entity: device_tracker....
>     gradual_opacity: 0.5
> ```
> 
> **Expected Behavior:**
> 
>     * The map should display correctly using the dynamic tile_layer_url that includes the latest version code from sensor.naver_map_version.
> 
> 
> **Actual Behavior:**
> 
>     * The map does not display; only the device tracker icons are visible on a blank background.
> 
>     * No errors appear in the browser console.
> 
>     * Using a static URL with a hardcoded version code works as expected.
> 
> 
> **Example of Working Static Configuration:** `tile_layer_url: "https://map.pstatic.net/nrb/styles/basic/1732841753/{z}/{x}/{y}@2x.png?mt=bg.ol.ts.ar.lko"`
> 
> **Additional Information:**
> 
> **Attempted Solutions:**
> 
>     * Used config-template-card to inject the dynamic URL, but encountered syntax errors or the map did not display.
> 
>     * Tested the sensor values, and they are correctly fetching the latest version code and constructing the URL.
> 
>     * Confirmed that the placeholders {z}, {x}, {y} are correctly used and not URL-encoded.
> 
> 
> **Environment Details:**
> 
>     * Custom Map Card Version: v1.6.0
> 
>     * No relevant errors appear in the Home Assistant logs.
> 
>     * Browser console does not show any errors when the map fails to display.
> 
> 
> **Question:**
> 
>     * Is it possible to support templating or placeholders in the tile_layer_url field of the custom map card to allow dynamic insertion of values like the version code?
> 
>     * If not currently supported, would it be possible to add this feature in a future update?

**Comment by nathan-gs** [comment]
Working on an implementation for this. Will ping when ready to test.

**Comment by nathan-gs** [comment]
@hyungynlim @bezmi I' ve implemented this in [v1.9.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.9.0), take a look at the docs for how it works.

**Comment by bezmi** [comment]
Thanks! It works pretty much perfectly. There are a couple of suggestions I have which I will open a new issue for, but I am just going to comment a working config example for anyone exploring this in the future. It works with the current latest release, v1.10.0. My setup for the template sensors is a bit convoluted, but essentially, I use the rest integration to store the data from: https://api.rainviewer.com/public/weather-maps.json as attributes. The value of `sensor.rainviewer_radar_selected_path` is set to `radar.past.i.path` or `radar.nowcast.i.path` from these rest sensors, where `i` is an index selected by an `input_number`. The value of `sensor.rainviewer_satellite_corresponding_path` is set to the `satellite.infrared.i.path` where the timestamp matches that of the radar selected path.

```yaml
type: custom:map-card
x: 35.1592
"y": 98.4423
zoom: 10
history_date_selection: false
history_start: 4 hours ago
entities:
  - entity: zone.somewhere
    history_show_lines: false
    history_show_dots: false
    size: 20
    color: rgba(0, 128, 128, 0.85)
  - entity: zone.bezmi_work
    history_show_lines: false
    history_show_dots: false
    size: 20
    color: rgba(0, 128, 128, 0.85)
  - entity: zone.home
    history_show_lines: false
    history_show_dots: false
    size: 20
    color: rgba(0, 128, 128, 0.85)
  - entity: person.bezmi
    size: 20
    history_show_dots: false
    color: rgba(121, 130, 52, 0.85)
  - entity: person.other
    color: rgba(212, 103, 128, 0.85)
    size: 20
    history_show_dots: false
theme_mode: auto
tile_layer_url: https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png
tile_layers:
  - url: >-
      https://tilecache.rainviewer.com{{states('sensor.rainviewer_satellite_corresponding_path')}}/256/{z}/{x}/{y}/0/1_0.png
    options:
      opacity: 0.3
  - url: >-
      https://tilecache.rainviewer.com{{states('sensor.rainviewer_radar_selected_path')}}/512/{z}/{x}/{y}/8/1_0.png
    options:
      opacity: 0.6
```
