### ISSUE TITLE
geo_location_sources

### ISSUE THREAD

**Issue by chaosad2802** [nathan-gs/ha-map-card#70]
Hi,
I use classic map-card to show lighting impacts from Blitzordnung with this code :

type: map
entities:
  - entity: zone.home
**geo_location_sources:
  - blitzortung**

Is it possible to add something like "geo_location_sources" in ha-map-card ?

**Comment by nathan-gs** [comment]
Implementation in HA frontend is defined here:
https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-map-card.ts

If I understand the workings correctly it will emit an event with a lat/long to be visualized on the map. 

@chaosad2802 do you know if this is a real entity?

**Comment by boozer2** [comment]
> @chaosad2802 do you know if this is a real entity?

I’ll answer since I’m also using this integration and your card - yes. Blitzortung automatically creates and removes geo_location entities for each lightning strikes based on how it’s configured. Here’s an example of one:
![IMG_5371](https://github.com/nathan-gs/ha-map-card/assets/50851629/51956352-09e8-4129-b500-b587a8b8cdbd)

Instead of the geo_location_sources I’m using the auto entities card to automatically populate the entities, and this works perfectly, so this may be a reasonable workaround if the feature doesn’t get implemented.

**Comment by chaosad2802** [comment]
Hi,
Thank you both for your answers.
I don't understand enough to do something alone! 😁
What did you do with auto entities card?

**Comment by boozer2** [comment]
And just in case it’s useful to anyone else, here’s the YAML I’m using.
```
type: custom:auto-entities
filter:
  include:
    - entity_id: geo_location.lightning_strike*
      options:
        display: icon
        size: 6
        color: yellow
    - entity_id: zone.home
      options:
        size: 32
  exclude: []
card:
  type: custom:map-card
  theme_mode: auto
  title: Lightning Strikes
  focus_entity: zone.home
  zoom: 8
  card_size: 9
  ```

The size and color attributes appear to only affect the circle around the entity, not the icon, but that’s a different issue.
