### ISSUE TITLE
Variable opacity based on time from history_end

### ISSUE THREAD

**Issue by mpipeling** [nathan-gs/ha-map-card#73]
Native HA map card plots points & connecting lines in history with increasing opacity over time [inversely] such that more recent points/path are darker (see below)

I can't find a way to (dynamically) adjust the opacity in ha-map-card [can use a fixed opacity for the entire path with history_line_color: rgba(255,0,255,0.6), for example]

Appears native HA map card creates "gradualOpacity" variable based on "pointIndex" & "opacityStep" 

Is it possible to have this functionality in ha-map-card?

[NATIVE]
![image](https://github.com/nathan-gs/ha-map-card/assets/117635277/eea6922d-d24c-4967-85c5-dfa39c62df27)
vs.
[HA-MAP-CARD]
![image](https://github.com/nathan-gs/ha-map-card/assets/117635277/88ab6528-90a3-474b-8a18-0540df13a10c)

**Comment by nathan-gs** [comment]
Fixed in [v1.5.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.5.0)

**Comment by ildar170975** [comment]
@nathan-gs 
1.5.1
Strange, I see no difference between "default settings" & "gradual_opacity: 0.5".
Please check this:
```
  - type: custom:map-card
    title: default
    entities:
      - <<: &ref_entity_settings
          entity: person.ildar
          display: marker
          history_start: 12 hours ago
          history_end: now
          color: red
    <<: &ref_card_settings
      tile_layer_url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
      card_size: 15

  - type: custom:map-card
    title: "gradual_opacity: 0.5"
    entities:
      - <<: *ref_entity_settings
        gradual_opacity: 0.5
    <<: *ref_card_settings
```
![image](https://github.com/user-attachments/assets/1ff36ee8-dfcb-4612-b795-efc029b52e4d)

**Comment by ildar170975** [comment]
@nathan-gs 
Please have a look at this picture:
![image](https://github.com/user-attachments/assets/462b728c-45ed-4d75-9071-b135f754dd35)

These are 4 similar cards:
-- 2 cards for a `device_tracker` entity, 2 cards for a associated `person` entity;
-- 2 cards w/o `gradual_opacity` defined, 2 cards with `gradual_opacity = 0.9`

Card-mod was used to hide a map & a marker (security reasons):
```
  - type: custom:map-card
    title: default
    entities:
      - entity: device_tracker.xxx
        <<: &ref_entity_settings
          display: marker
          color: red
    <<: &ref_card_settings
      history_start: 12 hours ago
      history_end: now
      card_size: 8
      card_mod:
        style:
          map-card-entity-marker $: |
            .marker :first-child {display: none}
          .: |
            .leaflet-tile-pane {display: none}

  - type: custom:map-card
    title: default
    entities:
      - entity: person.xxx
        <<: *ref_entity_settings
    <<: *ref_card_settings

  - type: custom:map-card
    title: "gradual_opacity: 0.9"
    entities:
      - entity: device_tracker.xxx
        <<: *ref_entity_settings
        gradual_opacity: 0.9
    <<: *ref_card_settings

  - type: custom:map-card
    title: "gradual_opacity: 0.9"
    entities:
      - entity: person.xxx
        <<: *ref_entity_settings
        gradual_opacity: 0.9
    <<: *ref_card_settings
```
Strangely the `gradual_opacity` does not seem to work for a `person` entity.
