### ISSUE TITLE
“size” and “color” entity attributes do not affect icon display

### ISSUE THREAD

**Issue by boozer2** [nathan-gs/ha-map-card#74]
When using “display: icon” for entities, the “size” and “color” attributes do not apply to the icon, only to the circle around the icon. I would expect this would change the size and color of the icon itself, or at least I would like a way to do that even if it’s a different attribute like “icon_size”.

Example YAML:
```
type: custom:map-card
entities:
  - entity: geo_location.lightning_strike_6ab35004ddee42cea27ed40b8568a710
    display: icon
    size: 6
    color: Yellow
  - entity: geo_location.lightning_strike_81cb982332524bc092e7c25b3dbd9b27
    display: icon
    size: 100
    color: Red
```

Example result:
![IMG_5373](https://github.com/nathan-gs/ha-map-card/assets/50851629/d2a4c8e3-d265-4830-b1ee-9e650bf83ac4)

The color only affects the circle around the displayed entity, and the size affects the size of the circle.

Also, for “display: icon” I would prefer no circle at all, or at least a way to remove it (which I can do now by using a very small “size”)

Thanks!

**Comment by nathan-gs** [comment]
A bit of a workaround, use the `style` property on the entity to override the color of the icon.

**Comment by nathan-gs** [comment]
Fixed in [v1.5.1](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.5.1)

**Comment by ildar170975** [comment]
Unfortunately, this change may be not desired in some cases.
Check this:
```
  - type: custom:map-card
    entities:
      - entity: device_tracker.iphone_5s_traccar
        display: icon
        color: red
        history_start: 12 hours ago
        history_end: now
      - entity: device_tracker.iphone_5s_32_traccar
        display: icon
        color: green
        history_start: 12 hours ago
        history_end: now
    tile_layer_url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    card_size: 10
```
A stock Map card will show:
-- tracks of different colors;
-- icons of SAME default color.
In most cases colors of tracks should be different, not colors of icons - circles of different colors will be rather enough.
Now we see this:
![image](https://github.com/user-attachments/assets/1d043c8c-942e-4d81-93ab-dc5f592cb469)

It could be even this with some default colors (if `color` options are not set):
![image](https://github.com/user-attachments/assets/6a350811-e6d5-4fc7-9ed4-69fb4fd020a8)
where you cannot see an icon at all.

**Proposal:** add a new option like `set_icon_color` (`true`/`false`), default is `false`. If `true` then the `color` is used for an icon too.
