### ISSUE TITLE
OpenWeather Weather Maps 2.0

### ISSUE THREAD

**Issue by GitHubGoody** [nathan-gs/ha-map-card#80]
What is the right configuration for [OpenWeather Weather Maps 2.0](https://openweathermap.org/api/weather-map-1h#layers)?

Here is an example config I'm using (API keys redacted):

```
type: custom:map-card
focus_entity: zone.home
zoom: 6
card_size: 10
entities:
  - entity: zone.home
    display: icon
    size: 40
tile_layers:
  - url: >-
      https://maps.openweathermap.org/maps/2.0/weather/1h/PR0/{z}/{x}/{y}?appid=<I have replaced this with my actual API key>
    options:
      attribution: <a href="https://openweathermap.org/">OpenWeatherMap</a>
      apikey: <I have replaced this with my actual API key>
```

It's not displaying anything and I've tried a few different <op> values. Does the attribution key need to be altered in some way?

**Comment by nathan-gs** [comment]
No, attribution is purely for the bottom notification. What does your browser console say under the networking tab? Normally you should see failed requests with a reason why.

You also don't need to specify `apikey`, just having `appid` should be enough.

**Comment by GitHubGoody** [comment]
Sorry, but I'm not following. What networking tab are you asking about?

**Comment by GitHubGoody** [comment]
@nathan-gs How does my config look for Maps 2.0? Is this what you need to help troubleshoot?

<img width="1234" alt="image" src="https://github.com/user-attachments/assets/91542f4a-c7dd-4f19-831b-7cb661993c95">

**Comment by nathan-gs** [comment]
Yes, but you need to look at it yourself. The issue is not with the Map Card, it's with the OGC of OpenWeatherMap 2.0.

**Comment by GitHubGoody** [comment]
Thank you. I see 9 requests initiated by map-card which return a 401 Unauthorized response.

**Comment by GitHubGoody** [comment]
@nathan-gs Is that 401 all you need to troubleshoot?

**Comment by GitHubGoody** [comment]
@nathan-gs Have you been able to get Maps 2.0 to work?

**Comment by nathan-gs** [comment]
401 means unauthorized, check how Maps 2.0 is authenticating vs 1.0. Best to see if you can get those responses working directly in the browser.

**Comment by GitHubGoody** [comment]
@nathan-gs By "working directly in the browser," what do you mean? I think we've reached the end of my understanding of the problem. Am I the only one using your map card who is interested in getting Maps 2.0 working? It seems this would have already been sorted out by someone who knows what they're doing already 😆

**Comment by GitHubGoody** [comment]
Are you suggesting just putting it all on one line because your example URL is not formatted for Weather Maps 2.0. I don't think putting it all on a single line matters since the originally formatting is provided in the map card example and it works fine with a Weather Maps 1.0 URL. I gave it a try anyways and nothing changes.

I decided to start trying to get Weather Maps 2.0 working again documenting a few different URL configurations.

First, here is the presented in the blog [Weather Maps 1.0 configuration](https://nathan.gs/2024/02/25/ha-map-card-displaying-weather-and-other-tilelayers/#creating-the-map):
```
type: custom:map-card
focus_entity: zone.home
zoom: 5
card_size: 10
entities:
  - entity: zone.home
    display: icon
    size: 40
tile_layers:
  - url: >-
      https://tile.openweathermap.org/map/clouds_new/{z}/{x}/{y}.png?appid=01234567890123456789012345678901
    options:
      attribution: <a href="https://openweathermap.org/">OpenWeatherMap</a>
      apikey: 01234567890123456789012345678901
```
That displays OK but as the blog post mentions "Unfortunately it’s a bit hard to read and there is no way to adjust the opacity in OpenWeatherMaps Maps 1.0 (there is in [2.0](https://openweathermap.org/api/weather-map-1h))."

So, I duplicated that card, clicked the 2.0 link, and then tried using its instructions to modify only the URL. Here are all of the URL's I tried:

1. The first API call format and parameters suggested using this as a starting point

`https://maps.openweathermap.org/maps/2.0/weather/1h/{op}/{z}/{x}/{y}?appid=01234567890123456789012345678901`

but with replacing the {op} with something from the list, so I chose TA2

`https://maps.openweathermap.org/maps/2.0/weather/1h/TA2/{z}/{x}/{y}?appid=01234567890123456789012345678901`

That seemed to be a URL that Map Card accepted because with the {op} placeholder in the URL, I was getting a `Error found in first run, check Console` message in the attribution line, but that message went away when replaced with TA2. However, I still did not see any information overlaid on the map. So, I tried every one of the {op} parameters. None of them displayed anything either.

Then, I noticed the opacity parameter and wondered if the default opacity was 0.0, so I tried a few different values between 0.0 and 1.0...

`https://maps.openweathermap.org/maps/2.0/weather/1h/TA2/{z}/{x}/{y}?opacity=0.9&appid=01234567890123456789012345678901`

That did not seem to help either and the default themes are listed lower in the blog post. All of them have a default opacity >0.0.

So, @nathan-gs I can open another issue if you'd like, but I'm still just trying to assess if my configuration is missing something required for Weather Maps 2.0. Would you mind taking a look at my troubleshooting above and let me know if I'm chasing my tail? Thank you!
