### ISSUE TITLE
History displays 2 paths

### ISSUE THREAD

**Issue by Elu43** [nathan-gs/ha-map-card#88]
Hello everyone, thank you for your work.

When using history, it seems the person points and the tracker points are now overlaid :

![image](https://github.com/user-attachments/assets/9b227950-9f67-41e5-acfa-746ffe783a40)

Points are created when the person changes its zone (home -> not_home, only 2 points are created with a straight line) and also when the device tracker updates its coordinates (a lot of points are created).

Is there a way to hide the person points and keep only the tracker ?

Best regards

**Comment by nathan-gs** [comment]
You could just use the device tracker? We are dependent on HA.

**Comment by Elu43** [comment]
Hi,

The problem is I have 2 trackers on the same person entity (car+phone) ...

**Comment by Valiante** [comment]
Using the person entity on a built-in map card works fine, no extra lines. The person only has one trackable device associated with them. The difference between using a person entity and a device entity is only apparent on the custom map card, when it appears to make no difference on a standard map card.

Example dashboard YAML below, and screenshots attached.

```
views:
  - title: HA Map Card
    type: panel
    cards:
      - type: map
        entities:
          - person.katie
        hours_to_show: 1
  - title: Custom Map Card
    type: panel
    cards:
      - type: custom:map-card
        entities:
          - person.katie
        history_start: 1 hour ago
```
HA Map Card with person entity:
![Screenshot_3-12-2024_134822_home-assistant-vm lan](https://github.com/user-attachments/assets/e4f79495-6243-45e4-a245-8d6d6eba112b)

Custom Map Card with person entity:
![Screenshot_3-12-2024_134754_home-assistant-vm lan](https://github.com/user-attachments/assets/523dd14c-04ae-4441-be38-35ef26773fea)

HA Map Card with device entity:
![Screenshot_3-12-2024_134938_home-assistant-vm lan](https://github.com/user-attachments/assets/151e0d1b-4e86-40f6-9eaa-459645306ea5)

Custom Map Card with device entity:
![Screenshot_3-12-2024_135017_home-assistant-vm lan](https://github.com/user-attachments/assets/498d8933-2ca4-4e98-8046-a54192b5cc13)

Person config showing one trackable device:
![Screenshot_3-12-2024_135051_home-assistant-vm lan](https://github.com/user-attachments/assets/616b8639-3f5f-4385-8133-72c793814962)
