### ISSUE TITLE
Unavailable device_tracker causes map to not draw anything

### ISSUE THREAD

**Issue by realzoulou** [nathan-gs/ha-map-card#91]
**Issue description:**
When device_tracker has state `Unavailable`, no map is drawn at all

**Expected:**
Map is drawn still but without the unavailable device_trackers (same behavior as with the HA included Map Card)

**Symptom:** ha-map-card shows "Error found in first run. check Console"
Console highlights map-card.js line https://github.com/nathan-gs/ha-map-card/blob/1cd63018e7a8723f6da54b29b62505471a033915/src/components/MapCard.js#L240 
```
238     // Get lat lng
239      let latLng = HaMapUtilities.getEntityLatLng(configEntity.id, hass.states);
240      const latitude = latLng[0] ?? null;
241      const longitude = latLng[1] ?? null;
```

map card configuration:
```
type: custom:map-card
title: Location history 24h
card_size: 6
zoom: 19
x: "11.000000"
"y": "48.000000"
tile_layer_url: >-
  https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
tile_layer_attribution: >-
  Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye,
  Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community
tile_layer_options:
  maxZoom: 19
  referrerPolicy: strict-origin-when-cross-origin
theme_mode: light
entities:
  - entity: device_tracker.uwb_anchor_a1
    display: marker
    size: 16
    color: grey
    z_index_offset: 0
  - entity: device_tracker.uwb_anchor_a3
    display: marker
    size: 16
    color: grey
    z_index_offset: 0
  - entity: device_tracker.uwb_anchor_a4
    display: marker
    size: 16
    color: grey
    z_index_offset: 0
  - entity: device_tracker.uwb_tag
    history_start: 1 hours ago
    focus_on_fit: false
    display: marker
    size: 20
    color: green
    z_index_offset: 40
    fallback_x: "11.00000"
    fallback_y: "48.00000"
```
![image](https://github.com/user-attachments/assets/8500329e-249d-489e-ad37-99a46a46b8c8)
