### ISSUE TITLE
history_date_selection not working

### ISSUE THREAD

**Issue by threadstone83** [nathan-gs/ha-map-card#98]
Hello,

today I tried to setup the ha-map-card. Here I also want to show a date-picker similar as shown here:
https://userbag.co.uk/development/home-assistant-exploring-location-history/

I thought the option history_date_selection=true will show such an date-picker but nothing changes. Only the map card will be shown. No oerlay, additional area,...

Am I wrong? Do I have to ass more than only this option?

By the way: I set up the card as a panel view in HA.

Thank you in advance.

Best regards
Andreas

**Comment by nathan-gs** [comment]
Have you added a `type: energy-date-selection` card? This one controls the widget.

**Comment by threadstone83** [comment]
@nathan-gs I tried different things:

1) I only added history_date_selection= true --> nothing happens
2) I tried the code from the link (here is a type: energy-date-selection card included). Here I got the map and the possibility to control the date, but I have not been able to adapt the code so that the map is displayed over the entire height and the selection field is only displayed small (overlay) (see image).

Do you have a suitable code (for the panel view) that you can send me or include as an example in your instructions?

![falsche_Ansicht](https://github.com/user-attachments/assets/8e393795-84fc-489d-b990-3b4b2ee8c76d)

**Comment by nathan-gs** [comment]
Something like this:

panel view:
```yaml
square: false
columns: 1
type: grid
cards:
  - type: vertical-stack
        cards:
          - type: custom:map-card # with more options
          - type: energy-date-selection
```
